name: Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.repository == 'JrMasterModelBuilder/homebrew-swftools'

    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Latest Download
        run: ./test/latest-download.sh

      - name: Check Latest HEAD
        run: ./test/latest-head.sh

      - name: Keep Alive
        uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
